# ${} values are taken from the env. vars set in ./.env file.

version: "3.8"
services:
  personal-website:
    image: personal-website-image
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
        PUBLIC_SERVER_LOCATION_ORIGIN: ${PUBLIC_SERVER_LOCATION_ORIGIN}
    container_name: personal-website-container
    ports:
      - "${PORT}:${PORT}/tcp"
    env_file:
      - .env